const DESKTOP_CARDS = 12;
const TABLET_CARDS = 8;
const MOBILE_CARDS = 5;
const DESKTOP_LOADED_CARDS = 3;
const TABLET_MOBILE_LOADED_CARDS = 2;
const DESKTOP_MIN_WIDTH = 1225;
const TABLET_MIN_WIDTH = 793;

export {
  DESKTOP_CARDS,
  TABLET_CARDS,
  MOBILE_CARDS,
  DESKTOP_LOADED_CARDS,
  TABLET_MOBILE_LOADED_CARDS,
  DESKTOP_MIN_WIDTH,
  TABLET_MIN_WIDTH,
}
